### ISSUE TITLE
feature request: bitcoin donation

### ISSUE THREAD

**Issue by juanjgit** [perseo22/pacmanager#17]
You really need a bitcoin donation button both in the app and in the home page.

**Comment by perseo22** [comment]
!?!?!?
What??

Heheheh....

Alright, alright, I'm really pleased to hear that, but well... you know...
donations are not going as well as I expected :( So, I have no faith that
they would increase in any manner.

Anyway, I have no idea on how to do that "Bitcoin" trick, where to start,
where to use those bitcoins once I receive them, ...

**Comment by juanjgit** [comment]
Some spam: http://www.juanj.com/blog/introduccion-al-bitcoin/

Just set up a wallet and add "Bitcoin donations: XXXXXXXX", where XXXX is your public address. Once you get some bitcoins you can spend them online, cash them out using bit2me or find a bar near you at https://coinmap.org and have a beer ;)

**Comment by perseo22** [comment]
Alright!
I did it!

Now I have a Bitcoin address (13i565MhfmfbuZmj91XUkDiaT2AEJmJucV), which
appears at my PAC Site https://sites.google.com/site/davidtv/
Let's see!! ;)

**Comment by juanjgit** [comment]
Issue cosed, as you now have your first bicoin donation ;)

Keep doing good work. PAC manager is awesome. Thank you.

**Comment by dandv** [comment]
I'd be happy to donate like $50 in BTC, but I'd like to know if you're still working on PAC Manager and can fix some of simple but blatant problems I've highlighted.
