### ISSUE TITLE
Ubuntu 17.10 Support

### ISSUE THREAD

**Issue by EliasKotlyar** [perseo22/pacmanager#69]
Unfortunately, i cannot make it work on Ubuntu 17.10. I installed a bunch of packages, and can start the PAC-Manager. As soon as i connect to a Server, i dont see any output. Its just a black Screen.

For now on, i was able to use the snap version:
```
sudo snap install pac-vs
```

**Comment by Prototype-X** [comment]
Try this https://github.com/asbru-cm/asbru-cm

**Comment by EliasKotlyar** [comment]
Thanks you!
