### ISSUE TITLE
Errore kubuntu 18.04

### ISSUE THREAD

**Issue by ruggeroland** [perseo22/pacmanager#76]
Hi, I have installed PAC on kubuntu 18.04
I installed everything via the terminal.
During the first installation it gave me error for missing packages and I tried with apt-get install -f and then I reinstalled PAC but when I try to start the program I only see the logo but it does not start.
can you help me?

**Comment by MrFishFinger** [comment]
Try using Asbru Connection manager:

https://github.com/asbru-cm/asbru-cm
https://www.asbru-cm.net/

It is a fork of PAC manager, and is actively maintained (PAC seems to be dead: https://github.com/perseo22/pacmanager/issues/57)

**Comment by ruggeroland** [comment]
thank you very much, I try now.
